from panel.bot_logic.browser import launch_browser
from panel.bot_logic.human_behavior import simulate_typing, random_wait
from panel.bot_logic.sms_handler import SMSHandler
from panel.bot_logic.captcha_solver import CaptchaSolver
from panel.bot_logic.email_verifier import EmailVerifier
from panel.models import InstagramAccount
from django.utils import timezone
import time

class AccountCreator:
    def __init__(self, username, password, email=None, proxy=None, headless=None, task=None):
        self.username = username
        self.password = password
        self.proxy = proxy
        self.headless = headless
        self.task = task
        self.logs_accumulator = ""
        
        self.sms = SMSHandler(logger=self.log)
        self.email_verifier = EmailVerifier(logger=self.log)
        self.captcha = CaptchaSolver(logger=self.log)
        
        # Use real temporary email address generated by the verifier API
        self.email = email
        if not self.email or "@tempmail" in self.email:
            self.email = self.email_verifier.get_email()

    def log(self, message):
        self.logs_accumulator += f"{timezone.now().strftime('%Y-%m-%d %H:%M:%S')} | {message}\n"
        print(f"[@{self.username}] {message}")
        if self.task:
            self.task.logs = self.logs_accumulator
            self.task.save()

    def run(self):
        playwright_instance = None
        browser = None
        context = None
        page = None
        try:
            self.log("Launching browser...")
            playwright_instance, browser, context, page = launch_browser(
                proxy=self.proxy, 
                headless=self.headless
            )
            
            self.log("Navigating to Instagram Sign-up page...")
            page.goto("https://www.instagram.com/accounts/emailsignup/", timeout=60000)
            random_wait()

            self.log(f"Filling out registration form: Email={self.email}, Username={self.username}")
            
            # Fill email
            simulate_typing(page, 'input[name="emailOrPhone"]', self.email)
            random_wait()

            # Full name
            simulate_typing(page, 'input[name="fullName"]', "John IGAuto")
            random_wait()

            # Username
            simulate_typing(page, 'input[name="username"]', self.username)
            random_wait()

            # Password
            simulate_typing(page, 'input[name="password"]', self.password)
            random_wait()

            # Submit registration form
            self.log("Submitting sign-up form...")
            page.click('button[type="submit"]')
            random_wait()

            # Solve Captcha if it appears
            if self.captcha.is_captcha_present(page):
                self.log("Captcha challenge detected. Attempting solve...")
                self.captcha.solve(page)
                random_wait()

            # Handle Phone Number Verification if Instagram intercepts the signup
            is_phone_verification = False
            try:
                # If page URL changed or specific elements are visible
                if page.locator('input[name="emailOrPhone"]').is_visible() or page.locator('text="Phone"').count() > 0:
                    is_phone_verification = True
            except Exception:
                pass

            if is_phone_verification:
                self.log("Phone verification triggered. Buying phone number...")
                phone_number, request_id = self.sms.get_number()
                self.log(f"Entering phone number: {phone_number}")
                page.fill('input[name="emailOrPhone"]', phone_number)
                page.click('button[type="submit"]')
                random_wait()

                self.log("Waiting for verification code SMS...")
                code = self.sms.wait_for_code(request_id)
                self.log(f"Submitting SMS verification code: {code}")
                page.fill('input[name="confirmationCode"]', code)
                page.click('button[type="submit"]')
                random_wait()

            # Check if email verification code is requested
            self.log("Checking if email verification link is required...")
            try:
                # Check for verification email from 1secmail and click confirmation link
                verify_url = self.email_verifier.get_verification_link()
                self.log(f"Navigating to confirmation URL: {verify_url}")
                page.goto(verify_url)
                random_wait()
                self.log("Email confirmation completed.")
            except Exception as e:
                self.log(f"Email verification step completed or skipped: {e}")

            # Complete registration check
            self.log("Waiting for signup finalization...")
            page.wait_for_timeout(10000)
            
            # Save account to Django Database
            account = InstagramAccount.objects.create(
                username=self.username,
                password=self.password,
                email=self.email,
                phone=phone_number if is_phone_verification else "",
                status='active'
            )
            
            self.log(f"✅ Instagram account @{self.username} created and saved successfully.")
            
            # Save cookie state for future logins
            from panel.bot_logic.social_actions import get_cookie_path
            context.storage_state(path=get_cookie_path(self.username))
            
            context.close()
            browser.close()
            playwright_instance.stop()
            return True

        except Exception as e:
            self.log(f"❌ Account creation failed: {e}")
            if context:
                try: context.close()
                except Exception: pass
            if browser:
                try: browser.close()
                except Exception: pass
            if playwright_instance:
                try: playwright_instance.stop()
                except Exception: pass
            raise e
